spring.http.multipart.maxFileSize: 10MB
spring.http.multipart.maxRequestSize: 10MB
spring.redis.host: 192.168.1.199
spring.redis.port: 6379
spring.data.mongodb.database: local
spring.data.mongodb.uri: mongodb://192.168.1.199:27017